feat(bin): Added bun support to outdated script

diff --git a/bin/outdated b/bin/outdated
--- a/bin/outdated
+++ b/bin/outdated
@@ -12,19 +12,20 @@ readonly COLOR_RESET=$(echo -e "\033[0;0m")
 
 readonly DATE_FORMAT="%Y-%m-%d %H:%M:%S%z"
 
+readonly BUN=${BUN:-1}
 readonly COMPOSER=${COMPOSER:-1}
-readonly YARN=${YARN:-1}
+readonly YARN=${YARN:-0}
 
-function log::info () {
+function log::info() {
     date +"${COLOR_YELLOW}[${DATE_FORMAT}]${COLOR_RESET} ${COLOR_GREEN}${1}${COLOR_RESET}"
 }
 
-function log::error () {
+function log::error() {
     date +"${COLOR_YELLOW}[${DATE_FORMAT}]${COLOR_RESET} ${COLOR_RED}${1}${COLOR_RESET}"
 }
 
-function is_installed () {
-    if ! command -v "$1" >/dev/null ; then
+function is_installed() {
+    if ! command -v "$1" >/dev/null; then
         log::error "Command ${COLOR_BLUE}${1}${COLOR_RED} not found in \$PATH, exiting"
         return 0
     fi
@@ -33,10 +34,10 @@ function is_installed () {
 }
 
 # Check for outdated composer dependencies
-function check::composer () {
+function check::composer() {
     log::info "Checking for local outdated composer dependencies..."
 
-    if [ ! -f composer.lock ]; then
+    if [[ ! -f composer.lock ]]; then
         log::error "Unable to find ${COLOR_BLUE}composer.lock${COLOR_RED} file, exiting"
         return
     fi
@@ -48,11 +49,25 @@ function check::composer () {
     }' | uniq | column -t
 }
 
+# Check for outdated bun dependencies
+function check::bun() {
+    log::info "Checking for local outdated bun dependencies..."
+
+    if [[ ! -f bun.lock ]]; then
+        log::error "Unable to find ${COLOR_BLUE}bun.lock${COLOR_RED} file, exiting"
+        return
+    fi
+
+    is_installed bun || return
+
+    bun outdated
+}
+
 # Check for outdated Node.js packages via yarn
-function check::yarn () {
+function check::yarn() {
     log::info "Checking for local outdated yarn dependencies..."
 
-    if [ ! -f yarn.lock ]; then
+    if [[ ! -f yarn.lock ]]; then
         log::error "Unable to find ${COLOR_BLUE}yarn.lock${COLOR_RED} file, exiting"
         return
     fi
@@ -65,5 +80,6 @@ function check::yarn () {
         } }' | uniq | column -t
 }
 
-[ "$COMPOSER" = 1 ] && check::composer
-[ "$YARN" = 1 ]     && check::yarn
+[[ "$BUN" == 1 ]] && check::bun
+[[ "$COMPOSER" == 1 ]] && check::composer
+[[ "$YARN" == 1 ]] && check::yarn
